-- MySQL Script generated by MySQL Workbench
-- Wed Jan 21 15:29:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E_COMMERCE
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRODUCT` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `idProduct` INT NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(100) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Package_Height` DECIMAL(5,2) NOT NULL,
  `Package_Width` DECIMAL(5,2) NOT NULL,
  `Package_Length` DECIMAL(5,2) NOT NULL,
  `Package_Weight` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SUPPLIER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SUPPLIER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SUPPLIER` (
  `idSupplier` INT NOT NULL,
  `Corporate_Name` VARCHAR(100) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(15) NOT NULL,
  `State` VARCHAR(15) NOT NULL,
  `City` VARCHAR(50) NOT NULL,
  `Street` VARCHAR(100) NOT NULL,
  `Zip_Code` CHAR(9) NOT NULL,
  `Numero` CHAR(5) NOT NULL,
  `Complemento` VARCHAR(100) NULL,
  `Phone` CHAR(11) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSupplier`),
  UNIQUE INDEX `Corporate_Name_UNIQUE` (`Corporate_Name` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CUSTOMER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CUSTOMER` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `Country` VARCHAR(15) NOT NULL,
  `State` VARCHAR(15) NOT NULL,
  `City` VARCHAR(50) NOT NULL,
  `Street` VARCHAR(100) NOT NULL,
  `Phone` CHAR(11) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Zip_Code` CHAR(9) NOT NULL,
  `First_Name` VARCHAR(100) NOT NULL,
  `Last_Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `Contato_UNIQUE` (`Phone` ASC) VISIBLE,
  UNIQUE INDEX `E-mail_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ORDERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ORDERS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ORDERS` (
  `idORDER` INT NOT NULL,
  `Created_At` DATE NOT NULL,
  `Estimated_Delivery_Date` DATE NOT NULL,
  `Shipping_Cost` DECIMAL(10,2) NOT NULL,
  `CUSTOMER_idCustomer` INT NOT NULL,
  `Status` ENUM("Processando", "Realizado", "Enviado", "Em Transito", "Entregue") NOT NULL,
  PRIMARY KEY (`idORDER`, `CUSTOMER_idCustomer`),
  INDEX `fk_Pedido_Cliente1_idx` (`CUSTOMER_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`CUSTOMER_idCustomer`)
    REFERENCES `CUSTOMER` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ORDER_ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ORDER_ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ORDER_ITEMS` (
  `PRODUCT_idProduct` INT NOT NULL,
  `ORDERS_idORDER` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `Unit_Price` DECIMAL(10,2) NOT NULL,
  `Shipping_Distance` DECIMAL(5,2) NOT NULL,
  `Shipping_Weight` DECIMAL(5,2) NOT NULL,
  `Shipping_Price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`PRODUCT_idProduct`, `ORDERS_idORDER`),
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`PRODUCT_idProduct` ASC) VISIBLE,
  INDEX `fk_ORDER_ITEMS_ORDERS1_idx` (`ORDERS_idORDER` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`PRODUCT_idProduct`)
    REFERENCES `PRODUCT` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_ITEMS_ORDERS1`
    FOREIGN KEY (`ORDERS_idORDER`)
    REFERENCES `ORDERS` (`idORDER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PRODUCT_SUPPLIER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRODUCT_SUPPLIER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PRODUCT_SUPPLIER` (
  `SUPPLIER_idSupplier` INT NOT NULL,
  `PRODUCT_idProduct` INT NOT NULL,
  PRIMARY KEY (`SUPPLIER_idSupplier`, `PRODUCT_idProduct`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`PRODUCT_idProduct` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`SUPPLIER_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`SUPPLIER_idSupplier`)
    REFERENCES `SUPPLIER` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`PRODUCT_idProduct`)
    REFERENCES `PRODUCT` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SELLER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SELLER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SELLER` (
  `idSeller` INT NOT NULL,
  `CNPJ` CHAR(14) NOT NULL,
  `Corporate_Name` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Phone` CHAR(11) NOT NULL,
  PRIMARY KEY (`idSeller`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `Corporate_Name_UNIQUE` (`Corporate_Name` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DISTRIBUTION_CENTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DISTRIBUTION_CENTER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `DISTRIBUTION_CENTER` (
  `idDistCenter` INT NOT NULL AUTO_INCREMENT,
  `Country` VARCHAR(15) NOT NULL,
  `State` VARCHAR(15) NOT NULL,
  `City` VARCHAR(50) NOT NULL,
  `Street` VARCHAR(100) NOT NULL,
  `Zip_Code` CHAR(9) NOT NULL,
  `Contact_Info` CHAR(11) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDistCenter`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `INVENTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INVENTORY` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `INVENTORY` (
  `idInventory` INT NOT NULL,
  `SELLER_idSeller` INT NOT NULL,
  `DISTRIBUTION_CENTER_idDistributionCenter` INT NOT NULL,
  PRIMARY KEY (`idInventory`, `SELLER_idSeller`, `DISTRIBUTION_CENTER_idDistributionCenter`),
  INDEX `fk_Estoque_Vendedor1_idx` (`SELLER_idSeller` ASC) VISIBLE,
  INDEX `fk_Estoque_Centro de Distribuicao1_idx` (`DISTRIBUTION_CENTER_idDistributionCenter` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Vendedor1`
    FOREIGN KEY (`SELLER_idSeller`)
    REFERENCES `SELLER` (`idSeller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_Centro de Distribuicao1`
    FOREIGN KEY (`DISTRIBUTION_CENTER_idDistributionCenter`)
    REFERENCES `DISTRIBUTION_CENTER` (`idDistCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `INVENTORY_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INVENTORY_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `INVENTORY_ITEM` (
  `INVENTORY_idInventory` INT NOT NULL,
  `PRODUCT_idProduct` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`INVENTORY_idInventory`, `PRODUCT_idProduct`),
  INDEX `fk_Estoque_has_Produto_Produto1_idx` (`PRODUCT_idProduct` ASC) VISIBLE,
  INDEX `fk_Estoque_has_Produto_Estoque1_idx` (`INVENTORY_idInventory` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_has_Produto_Estoque1`
    FOREIGN KEY (`INVENTORY_idInventory`)
    REFERENCES `INVENTORY` (`idInventory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estoque_has_Produto_Produto1`
    FOREIGN KEY (`PRODUCT_idProduct`)
    REFERENCES `PRODUCT` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `SELLER_PRODUCT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SELLER_PRODUCT` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `SELLER_PRODUCT` (
  `SELLER_idSeller` INT NOT NULL,
  `PRODUCT_idProduct` INT NOT NULL,
  PRIMARY KEY (`SELLER_idSeller`, `PRODUCT_idProduct`),
  INDEX `fk_Vendedor_has_Produto_Produto1_idx` (`PRODUCT_idProduct` ASC) VISIBLE,
  INDEX `fk_Vendedor_has_Produto_Vendedor1_idx` (`SELLER_idSeller` ASC) VISIBLE,
  CONSTRAINT `fk_Vendedor_has_Produto_Vendedor1`
    FOREIGN KEY (`SELLER_idSeller`)
    REFERENCES `SELLER` (`idSeller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendedor_has_Produto_Produto1`
    FOREIGN KEY (`PRODUCT_idProduct`)
    REFERENCES `PRODUCT` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `WALLET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WALLET` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `WALLET` (
  `idWALLET` INT NOT NULL,
  `Payment_Method_Type` VARCHAR(45) NULL,
  `CUSTOMER_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idWALLET`, `CUSTOMER_idCustomer`),
  INDEX `fk_Carteira_Cliente1_idx` (`CUSTOMER_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Carteira_Cliente1`
    FOREIGN KEY (`CUSTOMER_idCustomer`)
    REFERENCES `CUSTOMER` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `LEGAL_ENTITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEGAL_ENTITY` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `LEGAL_ENTITY` (
  `CNPJ` CHAR(14) NOT NULL,
  `CUSTOMER_idCustomer` INT NOT NULL,
  `Trade_Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CNPJ`, `CUSTOMER_idCustomer`),
  INDEX `fk_Pessoa Fisica_Cliente1_idx` (`CUSTOMER_idCustomer` ASC) VISIBLE,
  UNIQUE INDEX `Trade_Name_UNIQUE` (`Trade_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa Fisica_Cliente1`
    FOREIGN KEY (`CUSTOMER_idCustomer`)
    REFERENCES `CUSTOMER` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `INDIVIDUAL_PERSON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INDIVIDUAL_PERSON` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `INDIVIDUAL_PERSON` (
  `CPF` CHAR(11) NOT NULL,
  `CUSTOMER_idCustomer` INT NOT NULL,
  `Birth_Date` DATE NOT NULL,
  PRIMARY KEY (`CPF`, `CUSTOMER_idCustomer`),
  INDEX `fk_Pessoa Juridica_Cliente1_idx` (`CUSTOMER_idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa Juridica_Cliente1`
    FOREIGN KEY (`CUSTOMER_idCustomer`)
    REFERENCES `CUSTOMER` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PIX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIX` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PIX` (
  `idPIX` INT NOT NULL,
  `Bank_Institution` VARCHAR(20) NOT NULL,
  `WALLET_idWALLET` INT NOT NULL,
  `PIX_Key` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`WALLET_idWALLET`, `idPIX`),
  INDEX `fk_PIX_Carteira1_idx` (`WALLET_idWALLET` ASC) VISIBLE,
  UNIQUE INDEX `PIX_Key_UNIQUE` (`PIX_Key` ASC) VISIBLE,
  UNIQUE INDEX `idPIX_UNIQUE` (`idPIX` ASC) VISIBLE,
  CONSTRAINT `fk_PIX_Carteira1`
    FOREIGN KEY (`WALLET_idWALLET`)
    REFERENCES `WALLET` (`idWALLET`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CREDIT_CARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CREDIT_CARD` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CREDIT_CARD` (
  `idCard` INT NOT NULL AUTO_INCREMENT,
  `Tokenized_Card` VARCHAR(45) NOT NULL,
  `Last_4_Digits` CHAR(4) NOT NULL,
  `Brand` VARCHAR(20) NOT NULL,
  `Expiration_Date` DATE NOT NULL,
  `WALLET_idWALLET` INT NOT NULL,
  PRIMARY KEY (`idCard`, `WALLET_idWALLET`),
  UNIQUE INDEX `Numero_cartao_UNIQUE` (`idCard` ASC) VISIBLE,
  INDEX `fk_Cartao de Credito_Carteira1_idx` (`WALLET_idWALLET` ASC) VISIBLE,
  CONSTRAINT `fk_Cartao de Credito_Carteira1`
    FOREIGN KEY (`WALLET_idWALLET`)
    REFERENCES `WALLET` (`idWALLET`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `BANK_SLIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BANK_SLIP` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `BANK_SLIP` (
  `id_BankSlip` INT NOT NULL,
  `Barcode_Number` VARCHAR(100) NOT NULL,
  `Value` DECIMAL(10,2) NOT NULL,
  `Issue_Date` DATE NOT NULL,
  `Due_date` DATE NOT NULL,
  `WALLET_idWALLET` INT NOT NULL,
  PRIMARY KEY (`id_BankSlip`, `WALLET_idWALLET`),
  UNIQUE INDEX `Id_Boleto_UNIQUE` (`id_BankSlip` ASC) VISIBLE,
  INDEX `fk_Boleto Bancario_Carteira1_idx` (`WALLET_idWALLET` ASC) VISIBLE,
  UNIQUE INDEX `Barcode_Number_UNIQUE` (`Barcode_Number` ASC) VISIBLE,
  CONSTRAINT `fk_Boleto Bancario_Carteira1`
    FOREIGN KEY (`WALLET_idWALLET`)
    REFERENCES `WALLET` (`idWALLET`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PURCHASE_ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PURCHASE_ORDER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PURCHASE_ORDER` (
  `idPurchaseOrder` INT NOT NULL,
  `Created_At` DATE NOT NULL,
  `Status` ENUM("Processando", "Realizado", "Enviado", "Em Transito", "Entregue") NOT NULL,
  `SUPPLIER_idSupplier` INT NOT NULL,
  `DISTRIBUTION_CENTER_idDistCenter` INT NOT NULL,
  `Expected_Delivery_Date` DATE NOT NULL,
  PRIMARY KEY (`idPurchaseOrder`, `SUPPLIER_idSupplier`, `DISTRIBUTION_CENTER_idDistCenter`),
  INDEX `fk_Ordem de Compra_Fornecedor1_idx` (`SUPPLIER_idSupplier` ASC) VISIBLE,
  INDEX `fk_Ordem de Compra_Centro de Distribuicao1_idx` (`DISTRIBUTION_CENTER_idDistCenter` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Compra_Fornecedor1`
    FOREIGN KEY (`SUPPLIER_idSupplier`)
    REFERENCES `SUPPLIER` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Compra_Centro de Distribuicao1`
    FOREIGN KEY (`DISTRIBUTION_CENTER_idDistCenter`)
    REFERENCES `DISTRIBUTION_CENTER` (`idDistCenter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PO_ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PO_ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PO_ITEMS` (
  `idItem` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `Unit_Cost` DECIMAL(10,2) NULL,
  `PRODUCT_idProduct` INT NOT NULL,
  `PURCHASE_ORDER_idPurchaseOrder` INT NOT NULL,
  PRIMARY KEY (`idItem`, `PRODUCT_idProduct`, `PURCHASE_ORDER_idPurchaseOrder`),
  INDEX `fk_Itens Ordem de Compra_Produto1_idx` (`PRODUCT_idProduct` ASC) VISIBLE,
  INDEX `fk_Itens Ordem de Compra_Ordem de Compra1_idx` (`PURCHASE_ORDER_idPurchaseOrder` ASC) VISIBLE,
  CONSTRAINT `fk_Itens Ordem de Compra_Produto1`
    FOREIGN KEY (`PRODUCT_idProduct`)
    REFERENCES `PRODUCT` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens Ordem de Compra_Ordem de Compra1`
    FOREIGN KEY (`PURCHASE_ORDER_idPurchaseOrder`)
    REFERENCES `PURCHASE_ORDER` (`idPurchaseOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE ORDERS 
   MODIFY COLUMN Status enum("Delivered", "Shipped", "Cancelled", "Processing");

ALTER TABLE PURCHASE_ORDER
   MODIFY COLUMN Status enum("Delivered", "Shipped", "Cancelled", "Processing", "Pending");
